version: 2.1
defaults: &defaults
  parallelism: 1
  working_directory: ~/negotiator
  docker:
    - image: circleci/node:12.14.1
      environment:
        NODE_ENV: test

jobs:
  build:
    <<: *defaults
    steps:
      - run:
          name: Install Dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/negotiator
      - restore_cache:
          key: negotiator-cache-{{ checksum "package-lock.json" }}
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: negotiator-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: npm run test
      - persist_to_workspace:
          root: ~/negotiator
          paths:
            - coverage
            - package.json

workflows:
  version: 2.1
  commit:
    jobs:
      - build
      - test:
          requires:
            - build
