version: 2.1
defaults: &defaults
  parallelism: 1
  working_directory: ~/negotiator
  docker:
    - image: cypress/base:8
      environment:
        NODE_ENV: test

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/negotiator
      - restore_cache:
          key: v2-negotiator-cache-{{ checksum "package-lock.json" }}
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: v2-negotiator-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
            - ~/.cache
      - run:
          name: Run tests
          command: npm run test
      - persist_to_workspace:
          root: ~/negotiator
          paths:
            - coverage
            - package.json

workflows:
  version: 2.1
  commit:
    jobs:
      - build